import { Anchor } from "lucide-react";
import { ButtonLink } from "../components/ButtonLink";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

/**
 * Harbor House Editorial — Meet Mary.
 * Personal, spacious, and story-led. Original photographs are preserved as supplied.
 */

const heroImage = "/manus-storage/mary-lynch-meet-mary-hero_8902efd8.jpg";
const popImage = "/manus-storage/pop-and-baby-mary-boat_ef16c849.jpg";
const popVideo = "/manus-storage/pop-driving-the-boat-18s_cc3eaa8d.mp4";
const popVideoPoster = "/manus-storage/pop-driving-the-boat-thumbnail_d6758521.jpg";
const familyTravelPhoto = "/manus-storage/mary-family-travel_7af40885.jpg";
const chesapeakePhoto = "/manus-storage/mary-chesapeake-frenchies_ed69a28d.jpg";
const oriolesPhoto = "/manus-storage/mary-orioles-family_627afe9d.jpg";
const paperTexture = "/manus-storage/downsize-baltimore-paper-texture_268a29f4.png";
const contourTexture = "/manus-storage/downsize-baltimore-contour-lines_aaa317b7.png";
export default function MeetMary() {
  return <div className="meet-page">
    <SiteHeader theme="meet" />
    <main>
      <section className="meet-hero"><div className="meet-hero__photo"><img src={heroImage} alt="Mary Lynch seated on a cream sofa holding a Mary Lynch folder" /><span>01 / Meet Mary Lynch</span></div><div className="meet-hero__copy"><p className="meet-eyebrow">A clear-eyed, human approach</p><h1>Real estate is what I know.<br /><i>Helping families through change is why I do it.</i></h1><div className="meet-rule" /><p>Nearly three decades in residential real estate have taught me how much a home can hold. The plans, the people, the memories, and the next chapter are all part of the conversation.</p><ButtonLink theme="meet">Let’s Talk About What Comes Next</ButtonLink></div></section>

      <section className="meet-story"><div className="meet-story__aside"><p className="meet-eyebrow">The work behind the work</p><span>02</span><Anchor size={28} strokeWidth={1.1} /></div><div className="meet-story__body"><h2>A career in real estate.<br /><i>A purpose in helping families.</i></h2><p>For nearly 30 years, I have helped Baltimore-area families buy and sell homes. I began with first-time buyers, relocation, foreclosures, estates, and the many different ways real estate decisions can shape a family’s life.</p><p>Over time, the work became more focused. I began to see how housing decisions become more layered when family, aging, finances, belongings, health, and the future all arrive at the same table.</p><p>When you are younger, there are often opportunities for a do-over. When someone is making a housing decision at 70, 80, or 90, there may not be as many opportunities to get it wrong. Those decisions deserve more time, education, resources, and planning.</p><div className="meet-credentials"><span>30 years in residential real estate</span><span>Certified Senior Advisor</span><span>Certified Probate Real Estate Specialist</span><span>Chair and Founder, NAIPC Greater Baltimore</span></div><figure className="meet-story__personal-photo"><img src={oriolesPhoto} alt="Mary with family at Orioles Park" /></figure></div></section>

      <section className="meet-pop"><div className="meet-polaroid"><img src={popImage} alt="Mary as a child with her grandfather Pop on a boat" /><span>Me &amp; Pop. Long before I knew where this would lead.</span></div><div className="meet-pop__copy"><p className="meet-eyebrow meet-eyebrow--gold">For me, this is personal</p><h2>My Pop was my grandfather.<br /><i>He was also my anchor.</i></h2><p>He was technically my grandfather, but he functioned as my father figure, my constant, and my anchor. He spent nearly ten years caring for my grandmother as she lived with dementia, deeply committed to keeping her at home.</p><p>After she died, Pop and I had several wonderful years together. Later, he was diagnosed with cancer. I became his caregiver while also raising teenagers. Eventually, Pop moved into my home, where a hospital bed was placed in the living and dining area because the house had never been designed for caregiving or aging.</p><p>I remember thinking, <i>How did I not know this?</i> I had spent my career advising people about homes, and neither his home nor mine was prepared for what our family needed.</p><p className="meet-pop__closing">That experience changed the direction of my work. It taught me that earlier planning and better information can give families more choices, more autonomy, and more peace of mind.</p><div className="meet-pop__video"><video controls preload="metadata" poster={popVideoPoster} playsInline><source src={popVideo} type="video/mp4" /></video><p>Our guy, Pop. Still happiest at the helm.</p></div></div></section>

      <section className="meet-chapter"><div><p className="meet-eyebrow meet-eyebrow--gold">A story I now share</p><h2>“3 A.M. and<br /><i>Unprepared.”</i></h2></div><div><p>My caregiving experience with Pop eventually became part of the chapter <i>3 A.M. and Unprepared: A Caregiver’s Awakening</i>, published through the National Aging in Place Council in <i>Aging in Place Conversations: Caregivers Edition.</i></p><p>The story traveled beyond the page through Baltimore County libraries and became part of the path that connected my work with broader aging education, including the American Library Association’s Aging Together initiative.</p><p>Pop led to caregiving. Caregiving led to writing. Writing led to libraries and education, and to helping more families understand what preparation can make possible.</p><span className="meet-chapter__note"><Anchor size={16} /> Published chapter · Caregivers Edition</span></div></section>

      <section className="meet-purpose" style={{ backgroundImage: `linear-gradient(rgba(16,42,67,.96),rgba(16,42,67,.96)),url(${contourTexture})` }}><div className="meet-purpose__mark"><span>04</span><Anchor size={26} strokeWidth={1.1} /></div><div><p className="meet-eyebrow meet-eyebrow--gold">From experience to purpose</p><h2>Age Isn’t the Deciding Factor.<br /><i>The Whole Picture Is.</i></h2><p>I am not pro-move or pro-stay. I look beyond someone’s age and ask the bigger questions. Is the home accessible? Is the support system strong? What do transportation, social connection, maintenance, and finances look like? What happens if circumstances change?</p><p>Sometimes the answer is staying. Sometimes it is modifying the home. Sometimes it is moving. My role is to help people understand their choices before circumstances make the choice for them.</p></div></section>

      <section className="meet-life"><div className="meet-life__intro"><p className="meet-eyebrow">Mary outside of work</p><h2>Still very much<br /><i>a Maryland girl.</i></h2><figure className="meet-life__personal-photo"><img src={chesapeakePhoto} alt="Mary with family and Frenchies on the Chesapeake" /></figure><p>I love the “Smalltimore” nature of Baltimore, where somehow you still run into people you have known since elementary school.</p></div><div className="meet-life__details"><p>Within a few hours, I can be at the beach, in the mountains, in another major city, or out in horse country. I grew up riding horses and still love the quiet beauty of Maryland’s farms.</p><div className="meet-life__words"><span>Family</span><span>Fellowship</span><span>Friendship</span><span>Good food</span><span>Faith</span><span>Travel</span><span>Frenchies</span><span>Orioles &amp; Ravens</span></div><figure className="meet-life__personal-photo meet-life__personal-photo--orioles"><img src={familyTravelPhoto} alt="Mary with family while traveling" /></figure><p>I love a day at the beach, a good meal, and the kind of travel that makes me feel like I am learning something new. I have recently discovered deep-sea fishing, and I have realized that the older I get, the more I enjoy adventure.</p></div></section>

      <section className="meet-final" data-testimonial-reserve="meet-mary-closing" style={{ backgroundImage: `url(${paperTexture})` }}><div className="meet-final__frame"><p className="meet-eyebrow">Empowered, not overwhelmed.</p><h2>Let’s Talk About<br /><i>What Comes Next.</i></h2><p>My goal is for you to understand your choices, have access to real resources, and feel confident making the decision that is right for you.</p><p>Planning ahead is not only a gift you give yourself. It can also be a gift to the people you love, leaving clarity instead of unanswered questions.</p><p>You can do this. It just takes a place to start.</p><ButtonLink theme="meet">Schedule a Conversation</ButtonLink></div></section>
    </main><SiteFooter theme="meet" /></div>;
}
